// NOTE: This file is generated by uniwind and it should not be edited manually.
/// <reference types="uniwind/types" />

declare module 'uniwind' {
  export type UniwindConfig = {
    themes: readonly ['light', 'dark'];
  };
}

export {};
