name: 'Setup  Node + PNPM + Install Dependencies'
description: 'Setup  Node + PNPM + Install Dependencies'
inputs:
  APP_ENV:
    description: 'APP_ENV (one of): development, staging, production'
    required: true
    default: 'staging'
  AUTO_SUBMIT: ## TODO: we need to handle this too
    description: 'AUTO_SUBMIT (one of): true, false'
    required: true
    default: 'false'
  VERSION:
    description: 'VERSION (one of): latest, 0.0.0'
    required: true
    default: 'latest'
  ANDROID:
    description: 'run for ANDROID (one of): true, false'
    required: true
    default: 'true'
  IOS:
    description: 'run for IOS (one of): true, false'
    required: true
    default: 'false'
  EXPO_TOKEN:
    description: 'EXPO_TOKEN'
    required: true
    default: 'false'

runs:
  using: 'composite'
  steps:
      - name: 📦 Setup Expo and EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ inputs.EXPO_TOKEN }}

      - name: ⚙️ Run Prebuild
        run: pnpm prebuild:${{ inputs.APP_ENV }}
        shell: bash

      - name: 📱 Run Android Build
        if: ${{ inputs.ANDROID == 'true' }}
        run: pnpm build:${{ inputs.APP_ENV }}:android --non-interactive  --no-wait --message "Build  ${{ inputs.APP_ENV }} ${{ inputs.VERSION }}"
        shell: bash

      - name: 📱 Run IOS Build
        if: ${{ inputs.IOS == 'true' }}
        run: pnpm build:${{ inputs.APP_ENV }}:ios --non-interactive  --no-wait --message "Build ${{ inputs.APP_ENV }} ${{ inputs.VERSION }}"
        shell: bash