#!/usr/bin/env bash

function changed {
    git diff --name-only HEAD@{1} HEAD | grep "^$1" >/dev/null 2>&1
}

echo 'Checking for changes in bun.lockb...'

if changed 'bun.lockb'; then
    echo "📦 bun.lockb changed. Run bun install to bring your dependencies up to date."
    bun install
fi

echo 'You are up to date :)'

echo 'If necessary, you can run bun prebuild to generate native code.'

exit 0
